README.md

Update README.md with link to design spec

---

.github/release-drafter.yml

Update release-drafter.yml for repo specific name

---

plugin.yaml

add install binary script in install hooks

---

.github/workflows/build-and-release-snapshot-plugin.yml

fix(ci): Update goreleaser args field

---

.github/workflows/build-and-release-snapshot-plugin.yml

This PR fixes # https://github.com/meshery/helm-kanvas-snapshot/actions/runs/11764370268/job/32769439872

[chore] Fix file path for goreleaser

---

.github/workflows/build-and-release-snapshot-plugin.yml

[chore] fix file path

---

.github/.goreleaser.yml

This PR fixes # https://github.com/meshery/helm-kanvas-snapshot/actions/runs/11764510727/job/32769736416#step:5:87

[chore] Fix goreleaser

---

plugin.yaml

Bump Plugin Version

---

.github/.goreleaser.yml
cmd/kanvas-snapshot/cmd.go
main.go

This PR fixes the usage of env variable to make the released plugin usable.

[chore] Fix env variables

---

.github/workflows/kanvas.yaml

Based on https://github.com/layer5labs/kanvas-snapshot/releases

Bump Kanvas Snapshot version to v0.2.20

---

cmd/kanvas-snapshot/cmd.go

[debug] Trigger Workflow

---

cmd/kanvas-snapshot/cmd.go

This PR removes the debug statements that were added for confirming the release process and triggering of workflow

[chore] Remove Debug Statements

---

cmd/kanvas-snapshot/cmd.go

[chore] Fix typo

---

cmd/kanvas-snapshot/cmd.go

[debug] add debug statements

---

.github/workflows/first-time-contributor.yml
.github/workflows/kanvas.yaml

Signed-off-by: Lee Calcote <lee.calcote@layer5.io>

[ci][chore] upgrade workflow runner to ubuntu-24.04

---

cmd/kanvas-snapshot/cmd.go

Remove debug statements

---

.github/workflows/kanvas.yaml

This PR updates the Kanvas Snapshot version based on latest release [v0.2.32](https://github.com/layer5labs/kanvas-snapshot/releases/tag/v0.2.32).

Update Kanvas Snapshot version

---

.github/workflows/build-and-release-snapshot-plugin.yml
.github/workflows/error-codes-updater.yaml
.github/workflows/go-testing-ci.yml
.github/workflows/golangci-lint.yml
cmd/kanvas-snapshot/cmd.go
go.mod

This PR fixes failed release. https://github.com/meshery/helm-kanvas-snapshot/actions/runs/13224848446/job/36914410962
Relates to changes in https://github.com/meshery/helm-kanvas-snapshot/pull/86

[chore] Fix Failing Release

---

MAINTAINERS.md

This PR knowledge is @theBeginner86 and his work on the project.

Update MAINTAINERS: thebeginner86

---

.github/workflows/error-codes-updater.yaml
.github/workflows/go-testing-ci.yml
.github/workflows/golangci-lint.yml
.github/workflows/label-commenter.yml
.github/workflows/labeler.yml
.github/workflows/release-drafter.yml
.github/workflows/release-notes.yml
.github/workflows/slack.yml

Towards [issue](https://github.com/meshery/meshery/issues/13754).

[CI] Update from `ubuntu-22.04` to `ubuntu-24.04` in workflows

---

.github/workflows/labeler.yml

This PR is a security chore. The `labeler` action calls for these permissions - https://github.com/actions/labeler#permissions

[Security] Define permissions explicitly

---

.github/workflows/release-drafter.yml

This PR replaces the secret used.

[CI] Swap secret names for release-drafter.yml

---

.github/security-insights.yml
.github/workflows/build-and-release-snapshot-plugin.yml
.github/workflows/error-codes-updater.yaml
.github/workflows/first-time-contributor.yml
.github/workflows/go-testing-ci.yml
.github/workflows/golangci-lint.yml
Makefile
README.md
cmd/kanvas-snapshot/cmd.go
go.mod
main.go
plugin.yaml
scripts/utils.sh

This PR updates all the remaining occurrences of `meshery/helm-kanvas-snapshot` to `meshery-extensions/helm-kanvas-snapshot` as it is causing few workflows to get skipped. 
Example: https://github.com/meshery-extensions/helm-kanvas-snapshot/actions/runs/14560350582
Check all workflows that got recently skipped. https://github.com/meshery-extensions/helm-kanvas-snapshot/actions?query=is%3Askipped

[chore] Update meshery to meshery-extensions

---

.github/.goreleaser.yml
cmd/kanvas-snapshot/cmd.go
go.mod

Fixes https://github.com/meshery-extensions/helm-kanvas-snapshot/actions/runs/14560529197/job/40843214222

[chore] Fix Lint

---

scripts/install-binary.sh

fix: update util script directory path

---

cmd/kanvas-snapshot/cmd.go
main.go

- Update the version of meshkit logger

Update meshkit logger

---

cmd/kanvas-snapshot/cmd.go

- Remove Host from Meshery API request header

Update Meshery API request header

---

.github/workflows/kanvas.yaml

 Update kanvas snapshot github action
